# Generated by Django 5.0.1 on 2024-01-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_full_name_user_name_remove_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='u_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile_no',
            new_name='u_mobile_no',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='u_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='occupation',
            new_name='u_occupation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='u_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='u_status',
        ),
    ]
