# Generated by Django 5.0.1 on 2024-01-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_email_user_u_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_mobile_no',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_status',
            new_name='status',
        ),
    ]
