# Generated by Django 4.2.3 on 2024-02-05 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_u_email_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
