# Generated by Django 4.2.3 on 2024-02-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_policy_policy_publication_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='register_user',
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='bpl_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='disability_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='minority_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_bpl_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_disability_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_minority_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_residence_area',
            field=models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural'), ('BOTH', 'Both')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('LIFE', 'Life'), ('AUTO', 'Auto'), ('HOME', 'Home'), ('TRAVEL', 'Travel')], max_length=50),
        ),
    ]
