# Generated by Django 4.2.3 on 2024-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_user_register_user_alter_aadhar_bpl_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='cast',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='document',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
