# Generated by Django 4.2.3 on 2024-02-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_aadhar_cast_alter_aadhar_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar',
            old_name='aadhar_firstname',
            new_name='user_id',
        ),
    ]
